# Read the Docs configuration file for Sphinx projects

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
   - method: pip
     path: .
     extra_requirements:
       - theme_rtd 
       - extensions
  


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: irene/conf.py